# must be unique in a given SonarQube instance
sonar.projectKey=tv:genialist:pFramework-M3U

# --- optional properties ---

# defaults to project key
sonar.projectName=pFramework-M3U

# defaults to 'not provided'
sonar.projectVersion=1.0
 
# Path is relative to the sonar-project.properties file. Defaults to .
sonar.sources=src/main/java
sonar.exclusions=**/test_*.java

sonar.exclusions=**/filterous*.js,**/test*.java

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

#----- Default SonarQube server
sonar.host.url=http://localhost:19000

sonar.java.binaries=src/main/bin

# Excludes test file (Pierre)
sonar.exclusions=src/**/test_*.java
